---
title: "NOAA Atlantic Hurricane"
author: "Andrew & Ben"
date: "2024-10-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# loading packages needed
pacman::p_load(tidyverse, skimr, broom, GGally, lubridate)

# Changing the default theme
theme_set(theme_bw())

# read in the data set
hurricanes <- read.csv("storms.csv") 
hurricanes <- hurricanes |>
  mutate(
    date = as.POSIXct(paste(month, day, year, hour), format = "%m %d %Y %H"),
    )
```


```{r exploratory data analysis}
summary(hurricanes)


hurricanes |>
  dplyr::select(-name, -year, -month, -day, -hour, -category, -status, -date) |>
  ggpairs()

```
```{r exploratory data analysis}
hurricanes |> 
  pivot_longer(
    cols = c(lat, long, tropicalstorm_force_diameter, hurricane_force_diameter),
    names_to = "variable",
    values_to = "value"
  ) |> 
  
  # Setting the order of the levels of assessment to the column order in grades
  mutate(variable = as_factor(variable)) |> 
  
  # Creating a scatterplot for grades and the other 8 predictors
  ggplot(
    mapping = aes(
      x = value,
      y = wind
    )
  ) + 
  
  geom_point() +
  
  geom_smooth(
    method = "loess",
    formula = y~x,
    se = F
  ) +
  
  facet_wrap(
    facets = ~ variable,
    scales = "free_x",
    nrow = 2
  ) 
  
```
```{r exploratory data analysis}
hurricanes |>
  dplyr::select(where(is.numeric)) %>%  # Select only numeric columns
  ggcorr(
    low = "red3",         
    mid = "white",         
    high = "blue3",        
    label = TRUE,          
    label_round = 2,      
    angle = -45,          
    hjust = 1           
  )

```
## IncludingPlots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.



```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE,
 fig.align = "center")
# message = F,
# warning = F)

# Loading in the needed packages
pacman::p_load(tidyverse, lubridate)

# Changing default themes
theme_set(theme_bw())
theme_update(plot.title = element_text(hjust = 0.5),
 plot.subtitle = element_text(hjust = 0.5))

# Changing the default choice for how many decimal places are displayed
options(digits = 4)
```

## Introduction

## Getting the data

```{r}
# Loads in the data
hurricanes <- read.csv("storms.csv")

hurricanes_clean <- 
  hurricanes |> 
  mutate(
    date = make_datetime(year, month, day, hour)
  ) |> 
  select(-X, -year, -month, -day, -hour) |> 
  mutate(
    year = year(date),
    month = month(date, label = T, abbr = F),
    day = day(date),
    hour = hour(date)
  )
    ```
    
## Number of Storms per Year chart

```{r}
hurricanes_clean |> 
  summarize(count = n(),
            .by = year) |> 

ggplot(mapping = aes(
  x = year,
  y = count
)) + 
  geom_col(fill = "steelblue",
           color = "black") + 
  labs(title = "Number of Storms per Year",
       x = "Year",
       y = "Number of Storms")
```

```{r}
# Bar plot of storms by month
ggplot(data = hurricanes_clean, 
       mapping = aes(
         x = factor(month(date), levels = 1:12)
       )
) +
  geom_bar(
    fill = "steelblue",
    color = "black"
  ) +
  
  labs(title = "Monthly Distribution of Storms", 
       x = "Month",
       y = "Count")
```

```{r}

```


```{r}
hurricanes_clean |> 
  dplyr::select(where(is.numeric), -hour, -day, -year) |> 
  GGally::ggcorr(
    low = "red3",
    mid = "white",
    high = "steelblue",
    label = T,
    label_round = 2
  )
```

